export { HomePage } from './HomePage.jsx'
export { MainHomePage } from './MainHomePage.jsx'
export { NotFoundPage } from './NotFoundPage.jsx'
export { LoginPage } from './LoginPage.jsx'
export { RegisterPage } from './RegisterPage.jsx'